apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: c7cj
  name: c7cj
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: c7cj
        spec:
          containers:
          - image: busybox
            name: c7cj
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
