apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
spec:
  accessModes: 
    - ReadWriteOnce
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: normal
  hostPath:
    path: /etc/foo

