apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 113ng
  name: 113ng
spec:
  containers:
  - image: nginx
    name: 113ng
    resources: {}
    env:
    - name: ENVIRONMENT  
      valueFrom:
        configMapKeyRef:
          name: envcfgmap
          key: var1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
