apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: res-c-m
  name: res-c-m
spec:
  containers:
  - image: nginx
    name: res-c-m
    resources:
      requests:
        cpu: "0.25"
        memory: "250Mi"
      limits:
        cpu: "0.3"
        memory: "300Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
