apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 131sa
  name: 131sa
spec:
  containers:
  - image: busybox
    name: 131sa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
