apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "132"
  name: "132"
spec:
  containers:
  - image: nginx
    name: "132"
    ports:
    - containerPort: 80
    resources: {}
    readinessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
