apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "133"
  name: "133"
spec:
  containers:
  - image: nginx
    name: "133"
    ports:
    - containerPort: 80
    resources: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
