apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  volumes:
  - name: lifevol
    emptyDir: {}
  containers:
  - image: redis
    name: redis
    resources: {}
    volumeMounts:
    - name: lifevol
      mountPath: /data/redis 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
