apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls;sleep 3600
    image: busybox
    name: bb
 - args:
    - /bin/sh
    - -c
    - echo "Hello world";sleep 3600
    image: busybox
    name: bb2
    resources: {}
 - args:
    - /bin/sh
    - -c
    - echo "3rd";sleep 3600
    image: busybox
    name: bb3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
