apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secured
  name: secured
spec:
  securityContext:
    fsGroup: 3000
  volumes: 
  - name : data-vol
    emptyDir: {}
  containers:
  - image: nginx
    name: secured
    resources: {}
    volumeMounts:
    - name: data-vol
      mountPath: /data/app
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
