apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: bonomat/nodejs-hello-world
    name: hello
    ports:
    - containerPort: 3000
      name: nodejs-port
    readinessProbe:
      initialDelaySeconds: 2
      httpGet:
       port: nodejs-port
       path: /
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 8
      httpGet:
       port: nodejs-port
       path: /     
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
