apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: question-two-pod
  name: question-two-pod
  namespace: ggckad-s2
spec:
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: question-two-pod
    envFrom:
    - configMapRef:
        name: app-config    
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
