apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    type: old
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hi k8 Kubernetes! && sleep 3600']

