apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q3
  name: q3
  namespace: ggckad-s2
spec:
  securityContext:
    fsGroup: 3000
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: q3
    securityContext:
      runAsUser: 1000
  - image: kubegoldenguide/alpine-spin:1.0.0
    name: q3-b
    securityContext:
      runAsUser: 2000
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
