apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: pi
  name: pi
  namespace: default
  resourceVersion: "119439"
  selfLink: /apis/batch/v1/namespaces/default/jobs/pi
  uid: 5de4ddd4-8dc8-48d1-949c-061e95a97ab6
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 5de4ddd4-8dc8-48d1-949c-061e95a97ab6
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 5de4ddd4-8dc8-48d1-949c-061e95a97ab6
        job-name: pi
    spec:
      containers:
      - command:
        - perl
        - -Mbignum=bpi
        - -wle
        - print bpi(2000)
        image: perl
        imagePullPolicy: Always
        name: pi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
